#!/usr/bin/env bash

# 90° rotation
#xinput --set-prop 6 --type=float "Coordinate Transformation Matrix" 0 1 0 -1 0 1 0 0 1

# 270° rotation
xinput --set-prop 6 --type=float "Coordinate Transformation Matrix" 0 -1 1 1 0 0 0 0 1
